### ISSUE TITLE
AssertionError in while performing Minimum working example

### ISSUE THREAD

**Issue by Lilyoung2000** [mit-acl/gym-collision-avoidance#15]
Hello, i'm having trouble during execution of example.py 
AssertionError: The obs returned by the `step()` method observation keys is not same as the observation space keys, obs keys: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18], space keys: ['is_learning', 'num_other_agents', 'dist_to_goal', 'heading_ego_frame', 'pref_speed', 'radius', 'other_agents_states']
Looking forward to your reply, thanks！

**Comment by mfe7** [comment]
should be fixed now
