### ISSUE TITLE
ModuleNotFoundError: No module named 'scipy' when running example.sh

### ISSUE THREAD

**Issue by jx2518** [mit-acl/gym-collision-avoidance#18]
Hi, when trying to simulate the Minimun Working Example, I encountered the following issue where I was prompted that: _No module named 'scipy'_. However, I installed scipy/scipy3-python both using pip and apt-get already. Would this possibly be a problem because the codes aren't fully compatible with the new version of Python?

This problem showed up while I was using Python 3.10 in Ubuntu, I tried to downgrade Python to 3.9 but the issue persists.

Could you please help? Thank you so much!

<img width="548" alt="Scipy_bug" src="https://github.com/mit-acl/gym-collision-avoidance/assets/121977360/73e25bfb-5d99-4645-b6d3-6c931c52fe93">

**Comment by mfe7** [comment]
when you install scipy through apt it probably is installing the pkg within your system python environment. but the example script sources a virtual environment to run the python code inside of. i would suggest entering the virtualenv (usually something like `source venv/bin/activate`) then pip installing scipy within the virtualenv and it should address that issue. but, i'm surprised that scipy wasn't installed into the virtualenv using the install script

**Comment by jx2518** [comment]
Thank you very much! Yes I think running _install.sh_ installs everything needed except scipy. With manually installing it into the venv it is working now!
