### ISSUE TITLE
How Can I Import Customized Map?

### ISSUE THREAD

**Issue by jx2518** [mit-acl/gym-collision-avoidance#20]
Hi! Really sorry for the continuous questions! As I am exploring the project, I wanted to import customized maps. I do see that in the world_maps folder there are three maps, as well as [Map.py](https://github.com/mit-acl/gym-collision-avoidance/blob/release/gym_collision_avoidance/envs/Map.py) which sets up a map. But then I realized that the Map class is only imported by [collision_avoidance_env.py](https://github.com/mit-acl/gym-collision-avoidance/blob/release/gym_collision_avoidance/envs/collision_avoidance_env.py) but CollisionAvoidanceEnv class isn't subsequently imported by any one of the experiment python files such as [example.py](https://github.com/mit-acl/gym-collision-avoidance/blob/release/gym_collision_avoidance/experiments/src/example.py) and [run_full_test_suite.py](https://github.com/mit-acl/gym-collision-avoidance/blob/release/gym_collision_avoidance/experiments/src/run_full_test_suite.py). Therefore, I wonder where I can edit the map, say importing [001.png](https://github.com/mit-acl/gym-collision-avoidance/blob/release/gym_collision_avoidance/envs/world_maps/001.png)? Thank you very much for your time!

**Comment by mfe7** [comment]
Hi - no problem. I haven't tested the static map system extensively (or recently), but here are some thoughts.

The CollisionAvoidanceEnv class is somehow imported through the [gym.make line](https://github.com/mit-acl/gym-collision-avoidance/blob/903564097509e3fbdbbb850a3a89729a28377b81/gym_collision_avoidance/experiments/src/example.py#L25) in the experiment scripts (gym has a mechanism of registering environments to instantiate classes, but presumably one could simply instantiate the class directly).

In terms of specifying which map to use, I think the idea was to use an attribute in the [config](https://github.com/mit-acl/gym-collision-avoidance/blob/903564097509e3fbdbbb850a3a89729a28377b81/gym_collision_avoidance/envs/config.py#L21) to tell the environment to use a static map, then something like `env.set_static_map(".../map_filename.png")` to tell the environment which map to use [see here](https://github.com/mit-acl/gym-collision-avoidance/blob/903564097509e3fbdbbb850a3a89729a28377b81/gym_collision_avoidance/envs/collision_avoidance_env.py#L369C9-L369C23)?

If I remember correctly, my logic for checking collisions with the static map was quite inefficient and slows down the environment a lot, but maybe this provides a starting point.

**Comment by jx2518** [comment]
Thank you so much for the quick reply, and Yes I am able to import a new map! While I was editing the code there was a minor issue which lies on line 20 of [Map.py](https://github.com/mit-acl/gym-collision-avoidance/blob/903564097509e3fbdbbb850a3a89729a28377b81/gym_collision_avoidance/envs/Map.py). imresize() is deprecated in SciPy 1.0.0, and removed in 1.3.0; and I was able to work around chaning it to cv2: self.static_map = cv2.resize(src=self.static_map,dsize=dims,interpolation=cv2.INTER_NEAREST).

But there is a follow-up issue that I found out: figure 0 shows the paths agents take in the original map (no obstacle); they reach their destinations.
<img width="524" alt="image" src="https://github.com/mit-acl/gym-collision-avoidance/assets/121977360/351a1bf2-3749-4abc-939b-1ec950011286">

However, when I switched to 001.png as the map, the orange agent doesn't move, blue and green agent stops at some point before reaching their destinations. I suspect that they hit the wall and then stop. But the wall isn't shown in the gif file.
<img width="515" alt="image" src="https://github.com/mit-acl/gym-collision-avoidance/assets/121977360/574ee29f-ba5c-43be-a149-7003d3a70d52">

So, do you know how I can make the map visible in the gif file? Thank you very much for your help!

**Comment by mfe7** [comment]
The gif is generated by [combining](https://github.com/mit-acl/gym-collision-avoidance/blob/903564097509e3fbdbbb850a3a89729a28377b81/gym_collision_avoidance/envs/visualize.py#L40C14-L40C14) a bunch of png files (one per timestep), so you would probably just need to add the map image to the background in this [function](https://github.com/mit-acl/gym-collision-avoidance/blob/903564097509e3fbdbbb850a3a89729a28377b81/gym_collision_avoidance/envs/visualize.py#L90)

**Comment by jx2518** [comment]
Gotcha! Thank you very much!
