### ISSUE TITLE
Code request

### ISSUE THREAD

**Issue by anlanxuan** [mit-acl/gym-collision-avoidance#3]
Hello, Mr. Michael Everett!
I'm a graduate student in a university and I'm interested in your article on multi-agent robot navigation.In particular, I am very much involved in the study of Socially Aware Motion Planning with Deep Reinforcement Learning However, I cannot download the data you used in the school. I hope you can provide the code of this article and send it to me. I wish you a pleasant study!
                                                                                                                                  Thanks

**Comment by mfe7** [comment]
@anlanxuan Thanks for the interest. The code associated with that paper is included in this repo, in one of the subdirectiories called CADRL. We don't have documentation for training that policy from scratch, but you can load a pre-trained version in this repo using the CADRLPolicy.py wrapper. Some of that might be clarified by [our new documentation](https://gym-collision-avoidance.readthedocs.io/).

**Comment by anlanxuan** [comment]
Thank you very much for answering my questions. I believe this will be of great help to my research. Thank you again!
