### ISSUE TITLE
Loading weight problem

### ISSUE THREAD

**Issue by anlanxuan** [mit-acl/gym-collision-avoidance#4]
Dear Mr Everett：
      I've already loaded your collision avoidance system on the win10 platform and can run examp.py，but it was not found when running the nn_navigation_value_multi-py file
4_agents_dataset_value_train.p, how do I generate the .p file? I hope you can reply me in your busy schedule or give me some advice,Thank you again
                                                                                                                                            Yours
                                                                                                                                            Sincerely

**Comment by mfe7** [comment]
@anlanxuan sorry I didn't have notifications on and missed this message. I am hoping to release a more recent version of the training code in the coming weeks, but we won't be able to support the older pickle file method you've mentioned here.

**Comment by mfe7** [comment]
Hi @anlanxuan the training code for GA3C-CADRL is now released [here](https://github.com/mit-acl/rl_collision_avoidance)
