### ISSUE TITLE
Training source

### ISSUE THREAD

**Issue by Geonhee-LEE** [mit-acl/gym-collision-avoidance#5]
Thanks for your contribution for DRL with mobile robot.

I'm interested in DRL and mobile robot, I already read your works and want to training new one. But when I checked the your open source, there didn't exist training source since maybe license. If it is possible to add example training source such as default CADRL, it will be helpful really.  Just reading the docs is insufficient to implement the training source.

Regards.  

+ I want to get 'agents_dataset_value_train.p' dataset in order to train the model. Can I receive the files or know this components?

**Comment by mfe7** [comment]
Hi @Geonhee-LEE thanks for your interest in this project. I am hoping to release the training code within the next few weeks -- I can try to remember to send a message here once it's posted.

**Comment by mfe7** [comment]
Hi @Geonhee-LEE the training code for GA3C-CADRL is now released [here](https://github.com/mit-acl/rl_collision_avoidance), but we won't be able to support the older CADRL training code.
