### ISSUE TITLE
Could you please tell me where are the codes calculating the diffusion map? thanks.

### ISSUE THREAD

**Issue by CuriousCat-7** [mit-acl/gym-collision-avoidance#7]
According to the paper, and 
[envs/policies/CADRL/scripts/multi/nn_navigation_value_multi.py
line 1161](https://github.com/mit-acl/gym-collision-avoidance/blob/5dda5a2a1e146a249130a18dbbb7271f1d2c6c31/gym_collision_avoidance/envs/policies/CADRL/scripts/multi/nn_navigation_value_multi.py#L1125)

You use a diffusion map to calculate the local best value area, but I cannot find the code dealing with it.

**Comment by mfe7** [comment]
Hi @CuriousCat-7 , the diffusion map code was part of a prior research project and that code was never released to the public. This codebase currently supports open worlds (any obstacles are agents, who are possibly static), so from that perspective, euclidean distance would be a good heuristic for choosing a subgoal for the local planner. Diffusion distance is useful when the environment has a lot of structure that causes straight-line distance to be a poor heuristic. The code you've linked doesn't require a diffusion distance anyway, as it simply grabs the subgoal from the agent's state vector.

**Comment by CuriousCat-7** [comment]
Thank you for your reply. Would you like to publish the code about the diffusion map in the future, cause I really like the insight in it?

**Comment by mfe7** [comment]
Unfortunately I don't think there are any plans to release that software
